OPENAI_API_KEY = "sua-chave-openai"
POSTGRES_HOST = "seu_host_postgres"
POSTGRES_DB = "seu_banco"
POSTGRES_USER = "seu_usuario"
POSTGRES_PASSWORD = "sua_senha"
TESSERACT_PATH = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe"  # ou o caminho do seu sistema
